### ISSUE TITLE
"'audion' started debugging this browser" appears before "Web Audio" tab is opened

### ISSUE THREAD

**Issue by max-vogler** [GoogleChrome/audion#105]
When the Audion extension is installed, the intrusive debugging message appears immediately when the Chrome Dev Tools are opened - even if the Web Audio tab has not been opened yet.

![image](https://user-images.githubusercontent.com/864168/133637336-0bd47fca-2bde-4432-a89d-a8759e1a67a4.png)

I suggest (and am working on a PR) to wait until the DevTools panel is opened for the first time before attaching the Chrome Debugger. Ultimately, the warning message will only be shown after the user explicitly clicks on the Web Audio tab. Continuing to show the message immediately is annoying - e.g. when inspecting a different page and not looking at the Web Audio tab at all.

**Comment by freder** [comment]
... it appears in _every_ open tab, and clicking `cancel` or the close button has no effect.

**Comment by max-vogler** [comment]
You're right, @freder. I opened #107 for this.
