### ISSUE TITLE
"'audion' started debugging this browser" warning stays after DevTools are closed

### ISSUE THREAD

**Issue by max-vogler** [GoogleChrome/audion#107]
Even after closing Dev Tools or clicking "Cancel", the warning bar is still shown. This comes from audion re-attaching here:

https://github.com/GoogleChrome/audion/blob/ad80955e95f1253308327771560c485ab885a886/src/devtools/WebAudioEventObserver.js#L30-L37

Both possible [DetachReasons](https://developer.chrome.com/docs/extensions/reference/debugger/#type-DetachReason) are user initiated, so I think removing the re-attach logic is sensible.

Mentioned in https://github.com/GoogleChrome/audion/issues/105#issuecomment-921078491

**Comment by hoch** [comment]
This issue is fixed.
