### ISSUE TITLE
Garbage collection

### ISSUE THREAD

**Issue by JoachimBaba** [GoogleChrome/audion#113]
Hi,

I have a question regarding the behavior of the extension.
When I was using Web Audio Inspector I noticed that the nodes in my app were piling up.
I was implementing a fix to make sure to disconnect the unused nodes properly but then Audion was introduced.

Using Audion, I check on the version my code where the nodes were piling up and the ones that are unused seems to be discarded now.
Can anybody confirm that garbage collection is actually at work here ?

I have issues monitoring the memory and the theory on the nodes's garbage collection is quite nebulous.
So I can't really make up my mind if Web Audio Inspector had issues displaying the nodes that were garbage collected or if it is Audion that's discarding the AudioBufferSourceNode that already played but are still connected.

If it is the case, then I don't necessarily need to disconnect the used nodes.
Thanks

**Comment by max-vogler** [comment]
Maybe @hoch can give more authoritative answers here, but I assume that letting a non-looping AudioBufferSourceNode  complete it's playback or calling stop and removing any reference to it should trigger garbage collection - calling disconnect manually should not be needed. Be aware that the timing of garbage collection is explicitly unspecified - the exact point in time when GC kicks in and what is collected is not specified and can change with future browser versions.

IIRC, older versions of the Web Audio Chrome Extension were prone to keeping references to AudioNodes which might result in prevention of garbage collection. The current audion version never accesses your AudioNodes - it receives the metadata through special Chrome Debugging APIs.

**Comment by hoch** [comment]
A great explanation, @max-vogler! I don't have anything to add here. :)

**Comment by JoachimBaba** [comment]
This clear things up.
Thank you for your answer @max-vogler

**Comment by benpigchu** [comment]
You can manually trigger a GC in memory tab of the devtool. If your nodes disappear after that, the GC is working on your nodes.

**Comment by hoch** [comment]
Closing per https://github.com/GoogleChrome/audion/issues/113#issuecomment-968673333.
