### ISSUE TITLE
Nodes connection order seems to be important 

### ISSUE THREAD

**Issue by Megaemce** [GoogleChrome/audion#117]
Hello team. I'm debugging my own app ([mobbler](https://mobbler.js.org)) and while doing so I noticed strange bug.  I have a vibrato effect with custom audioNode-like property: 

````javascript
 module.audioNode = {
        delayNode: new DelayNode(audioContext, { delayTime: delayTime }),
        inputNode: new GainNode(audioContext),
        outputNode: new GainNode(audioContext),
        depthNode: new GainNode(audioContext, { gain: width }),
        oscillatorNode: new OscillatorNode(audioContext, { type: "sine", frequency: speed }),
        get speed() {
            return this.oscillatorNode.frequency;
        },
        get width() {
            return this.depthNode.gain;
        },
        connect(destination) {
            if (destination.inputNode) this.outputNode.connect(destination.inputNode);
            else this.outputNode.connect(destination);
        },
        disconnect() {
            this.outputNode.disconnect();
        },
    };
};

module.audioNode.inputNode.connect(module.audioNode.delayNode);
module.audioNode.delayNode.connect(module.audioNode.outputNode);
module.audioNode.oscillatorNode.connect(module.audioNode.depthNode);
module.audioNode.depthNode.connect(module.audioNode.delayNode.delayTime);

module.audioNode.oscillatorNode.start(0);
````
and that's giving below result:
![image](https://user-images.githubusercontent.com/1651451/147812618-e298b51d-7a36-46e1-9a3a-b753938f033e.png)

where, when I reorder one line (for example oscillatorNode > depthNode) like so:
````javascript
module.audioNode.inputNode.connect(module.audioNode.delayNode);
module.audioNode.delayNode.connect(module.audioNode.outputNode);
module.audioNode.depthNode.connect(module.audioNode.delayNode.delayTime);
module.audioNode.oscillatorNode.connect(module.audioNode.depthNode); // just one line down
````
I can see: 
![image](https://user-images.githubusercontent.com/1651451/147812760-016c7256-e3a6-47ef-841b-ec8271d21e5a.png)

and that's even worse when connection-train looks like so:
````javascript
module.audioNode.depthNode.connect(module.audioNode.delayNode.delayTime);
module.audioNode.inputNode.connect(module.audioNode.delayNode);
module.audioNode.oscillatorNode.connect(module.audioNode.depthNode);
module.audioNode.delayNode.connect(module.audioNode.outputNode);
````
then the whole audion section looks just weird:
![image](https://user-images.githubusercontent.com/1651451/147812848-cd19abcd-444e-4618-89d1-9fb79bc2de12.png)

I can tell that order doesn't impact web audio itself - effect works just fine. It's just an audion issue which seems to be looking at the order of connection train (which - IMO - should not be important at all)

Another thing worth looking at is why DelayNode is not showing it's delayTime audioParam in this chart.

**Comment by hoch** [comment]
Thanks for the detailed bug reporting. We'll be picking up this project soon (Q1 2022) and address bugs filed in the tracker.

**Comment by hoch** [comment]
Can you try against the current main branch? I am not sure how to reproduce this issue on your app.

When I tried the "vibrato effect" on the app, now I see a different graph from the first screenshot in the report.

**Comment by Megaemce** [comment]
That seems to be working better now. Thank you
