### ISSUE TITLE
latest chrome cannot render graph visualizer

### ISSUE THREAD

**Issue by penghaoas** [GoogleChrome/audion#140]
![image](https://user-images.githubusercontent.com/11519526/164965920-73c3267c-181e-409f-a91b-522360011903.png)

ua: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36
os: macOS Monterey 12.0.1 (21A559)

**Comment by hoch** [comment]
Can you provide a link for a reproduction?

**Comment by hoch** [comment]
Again, without a reproduction we can't start working on the fix. I'll leave this open another week.

**Comment by hoch** [comment]
Closing - no activities.
