### ISSUE TITLE
Can Audion work in Electron?

### ISSUE THREAD

**Issue by marcelblum** [GoogleChrome/audion#141]
Has anyone been able to use this extension successfully in Electron? It may just be that Audion uses parts of the Chrome Extensions API that are unsupported in Electron (see [session.loadExtension()](https://www.electronjs.org/docs/latest/api/extensions)) but I don't know enough about the internals of extensions to be sure that this is the problem I'm running into so I didn't want to give up before posting here.

Here's how far I've gotten - I've built the extension from source and it loads and works fine in Chrome using `Load unpacked`. When I try to load it in Electron with `loadExtension()`, no exceptions are thrown, I can inspect the returned Audion extension object and it looks as expected, and the `extension-ready` event successfully fires. But the Web Audio panel never appears in the dev tools, and I get a couple of CLI console warnings:
`Permission 'debugger' is unknown or URL pattern is malformed.`
and
`Uncaught TypeError: Cannot read property 'attach' of undefined`
Is it impossible?

**Comment by hoch** [comment]
A bug is filed against Electron. Closing.

Thanks for bringing this to our attention!
