### ISSUE TITLE
Stale BaseAudioContexts in the drop-down menu

### ISSUE THREAD

**Issue by hoch** [GoogleChrome/audion#142]
* The issue was reported internally on 3/29.

Stale BaseAudioContexts are not being removed from the menu even after pressing “GC” button.

![Screen Shot 2022-04-28 at 2 23 20 PM](https://user-images.githubusercontent.com/676891/165848221-765b7c77-2918-466a-b57b-0a1196d3f61e.png)

Reproduction
1. Go to: https://googlechromelabs.github.io/web-audio-samples/audio-worklet/
   - There’s 1 OAC (OfflineAudioContext) “A” in the menu.
2. Then go to: https://googlechromelabs.github.io/web-audio-samples/audio-worklet/basic/hello-audio-worklet/
   - Now you can see 2 OACs and 1 AC. OAC “A” still exists in the menu even after navigating away from the page (i).
3. If you navigate between pages multiple times, you can see the menu list is getting bigger and bigger.
4. Pressing the trash can button (GC) doesn’t make any difference.

#138 is supposed to fix this, but this still reproduces in main branch (https://github.com/GoogleChrome/audion/commit/ee95b6f734f3e8f6f1a06d14d25b531d6be3a983).

**Comment by richnoah** [comment]
@hoch https://googlechromelabs.github.io/web-audio-samples/audio-worklet/basic/hello-audio-worknodlet/ is returning an error 404.

**Comment by hoch** [comment]
The link updated. There was a typo.

**Comment by richnoah** [comment]
@hoch @mzgoddard I was able to replicate the growing list of offline entries in the menu.  I also noticed that when I was https://googlechromelabs.github.io/web-audio-samples/audio-worklet/basic/noise-generator/ and hit refresh on the browser that the number of OAC entries on the menu increased by one each time.

Steps to reproduce:

1.  Open up Chrome
2. Open DevTools (ensure Web Audio shows as a tab in DevTools - if not acquire Audion)
3. Go to https://googlechromelabs.github.io/web-audio-samples/audio-worklet/
4. Check the drop-down menu in Web Audio DevTools to ensure (no recordings) is the only entry present
5. Click/Tap https://googlechromelabs.github.io/web-audio-samples/audio-worklet/basic/noise-generator/
6. Check the drop-down menu and see one offline entry and one real-time entry
7. Click/Tap back on the browser
8. Check the drop-down menu and see two offline entries
9. Click/Tap https://googlechromelabs.github.io/web-audio-samples/audio-worklet/basic/bit-crusher/
10. Check the drop-down menu and see three offline entries and one real-time entry
11. Click/Tap refresh on the browser
12. Check the drop-down menu and see four offline entries and one real-time entry
13. Click/Tap refresh on the browser
14. Check the drop-down menu and see five offline entries and one real-time entry

OS: MacOS 12.3.1 (Intel)
Browser: Chrome Version 100.0.4896.127 (Official Build) (x86_64)
Extentions: Aduion version 3.0.5

I also noticed the following errors in the console.  These were present for both the of the test urls I noted above:

- Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
- DevTools failed to load source map: Could not load content for https://googlechromelabs.github.io/web-audio-samples/assets/milligram.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by richnoah** [comment]
Upon further discovery it was determined that the following error is being produced when refreshing or navigating:

`Unchecked runtime.lastError: {"code":-32000,"message":"Cannot find BaseAudioContext with such id."}`

The error is unchecked and causes an unknown state.

@hoch would you please try and reproduce by opening an inspector on the Web Audio panel and confirm if you also see the same error message as above.

**Comment by hoch** [comment]
I can try, but this can be fixed by swallowing the error if there's no matching ID in the application or the dropdown menu. What do you think, @mzgoddard?

**Comment by hoch** [comment]
Friendly ping - @richnoah @mzgoddard!

**Comment by hoch** [comment]
Confirmed the fix locally. Thanks @richnoah and @mzgoddard!
