### ISSUE TITLE
Cannot see AudioWorklet subclasses in the inspector

### ISSUE THREAD

**Issue by micbuffa** [GoogleChrome/audion#84]
Hi! We're using FAUST to compile audio effects to WebAssembly and we use a sublclass of AudioWorklet to load the wasm file. When we connect the instance of this AW sublcass to our WebAudio graph, the inspector does not show it at all. Try this with canary: https://wasabi.i3s.unice.fr/WebAudioPluginBank/testers/zitashow1.html
![empty host 2018-04-09 17-59-59](https://user-images.githubusercontent.com/648664/38508588-e0a85626-3c1f-11e8-92aa-a591d13a9896.png)

See this image:
![empty host 2018-04-09 17-56-23](https://user-images.githubusercontent.com/648664/38508538-b9827cca-3c1f-11e8-9803-dd09080bfd41.png)

**Comment by hoch** [comment]
This is expected - the Audion currenlty does not have a wrapper for the AudioWorkletNode.

**Comment by micbuffa** [comment]
Ok, thanks... I didn't know if it was a bug.....

**Comment by olilarkin** [comment]
Any chance AudioWorklet support might be added?

**Comment by hoch** [comment]
@olilarkin Currently the project is not actively maintained. We are discussing the future of this project and will publish the team's decision soon.

**Comment by olilarkin** [comment]
Thank @hoch, it's a shame, it's a useful tool

**Comment by hoch** [comment]
Oh, I am integrating all the functionalities (with a lot of improvements) to Chrome DevTools. The process has started, but it is just taking a while to the official launch.

**Comment by olilarkin** [comment]
great news
