### ISSUE TITLE
Web Audio graph not appearing for local file

### ISSUE THREAD

**Issue by davidryan59** [GoogleChrome/audion#89]
I am developing a website that uses Web Audio nodes.

When I view my website online, I can see the audio graph via this extension.

When I am coding locally and viewing the local html file in Chrome, the Web Audio tab is blank, no audio graph is visible.

Why is this? Can it be fixed, I need to know what my graph structure looks like when I'm developing? Thanks!

**Comment by distante** [comment]
You could maybe run a local server and open your website there.

**Comment by meleyal** [comment]
@davidryan59 you could use python for this as detailed [here](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server#Running_a_simple_local_HTTP_server), or alternatively [serve](https://rubygems.org/gems/serve) (Ruby)  or [serve](https://www.npmjs.com/package/serve) (Node.js).
