### ISSUE TITLE
"Audion could not identify the object calling 'connect'” warning | No MediaStreamAudioSourceNode element

### ISSUE THREAD

**Issue by Mazamazine** [GoogleChrome/audion#91]
In my code, this warning appears when trying to connect a MediaStreamAudioSourceNode into an analyzer:

`Audion could not identify the object calling "connect":`
_`MediaStreamAudioSourceNode { ... }`_

 So, I guess this is why I don't see my MediaStreamAudioSourceNode in the graphs...?

In a [stackoverflow post](https://stackoverflow.com/questions/54640631/how-to-fix-audion-could-not-identify-the-object-calling-connect-error-when-t), someone said (February):

> I think the problem is that Audion still patches the prototype of the BaseAudioContext but a recent change in the spec moved functions like createMediaElementSource() to the AudioContext prototype. I will go ahead and create an issue for that on GitHub which will hopefully get fixed at some point.

> That being said, it's just a warning and it should not stop your website from working correctly.

By the way, I thought something was wrong in my code as the nodes was accumulating instead of being trashed by the garbage collector. Seems like it's due to the extension (supposedly reported in june - see the chrome webstore reviews)? Any possibility to activate the garbage collector in the visuals?

**Comment by kn0ll** [comment]
i had luck with the connect issue by changing `context.createMediaStreamSource()` to `new MediaStreamAudioSourceNode(context)`.

i do see buffers i believe to be garbage collected showing in the UI still though. :)
